### ISSUE TITLE
Archlinux and the Linux 3.1 update

### ISSUE THREAD

**Issue by jyaworski** [nbigaouette/acpi-eeepc-generic#21]
Upon using the function buttons, a notification about undefined-group/action is displayed on every key.

**Comment by tumpio** [comment]
Is it possible to work acpi-eeepc-generic to function with eeepc-wmi module?

That is loaded on 1215B, and trying to load eeepc-laptop gives no such device error:

```
modprobe: ERROR: could not insert 'eeepc_laptop': No such device
```

**Comment by ghthor** [comment]
The `eeepc_laptop` module has been deprecated in favor of the `asus-wmi` module. Last I checked my eeepce had everything working as expected using the `asus-wmi` module and NOT using this set of ACPI based listeners.

You should load the wmi's set of modules can check that x.org is outputing the correct keysyms for each of the func keys. If it isn't, then I don't know what could be wrong _-_

**Comment by tumpio** [comment]
ok, thanks for your reply ghthor.

**Comment by nbigaouette** [comment]
As ghthor mentioned, I believe acpi-eeepc-generic is not required anymore. The kernel should emit the proper symbols that window managers interpret directly, without needing acpid.
